@startuml
actor Aluno as aluno
participant "AlunoController" as controller
participant "AlunoService" as service
participant "MeritSystemContext" as dbContext
database "Banco de Dados" as db

aluno -> controller : solicitarListagemDeVantagens(alunoID)
controller -> service : listarVantagensParaAluno(alunoID)
service -> dbContext : acessarDbSetsDeVantagens(alunoID)
dbContext -> db : executarConsultaVantagens(alunoID)
db --> dbContext : listaDeVantagens
dbContext --> service : listaDeVantagens
service --> controller : listaDeVantagens
controller --> aluno : exibirListaDeVantagens(listaDeVantagens)
@enduml
