@startuml
left to right direction

node "Navegador Web" as navegador {
    [Browser]
}

node "Servidor Spring Boot" as spring {
    
    component "Controller" as controller {
        [AlunoController]
        [ProfessorController]
        [EmpresaController]
        [VantagemController]
        [TransacaoController]
        [CodigoResgateController]
    }
    
    component "Service" as service {
        [AlunoService]
        [ProfessorService]
        [EmpresaService]
        [VantagemService]
        [TransacaoService]
        [CodigoResgateService]
    }
    
    component "Repository" as repository {
        [AlunoRepository] 
        [ProfessorRepository] 
        [EmpresaRepository] 
        [VantagemRepository]
        [TransacaoRepository]
        [CodigoResgateRepository]
    }
}

node "Banco de Dados" as banco_dados {
    [MySQL Database]
}


navegador --> controller : HTTP/HTTPS
controller --> service 
service --> repository 
repository --> banco_dados : TCP/IP

@enduml
