@startuml
left to right direction

package "Navegador Web" as navegador {
    [Cliente]
}

package "Servidor ASP.NET Core" as aspnet {
    
    package "Controllers" as controllers {
        [AlunoController]
        [ProfessorController]
        [EmpresaController]
        [VantagemController]
        [TransacaoController]
        [CodigoResgateController]
    }
    
    package "Services" as services {
        [AlunoService]
        [ProfessorService]
        [EmpresaService]
        [VantagemService]
        [TransacaoService]
        [CodigoResgateService]
    }
    
    package "Data Context" as context {
        [MeritSystemContext]
    }
}

package "Banco de Dados" as banco_dados {
    [Database]
}

navegador --> controllers : HTTP/HTTPS
controllers --> services 
services --> context : DbSets (via MeritSystemContext)
context --> banco_dados : TCP/IP

@enduml
