@startuml Cadastro de Vantagem
actor User as "Usuário"
participant "VantagemController" as Controlador
participant "VantagemService" as service
participant "MeritSystemContext" as dbContext
database "Banco de Dados" as db

User -> Controlador: cadastrarVantagem(VantagemDTO)

Controlador -> service: cadastrarVantagem(vantagem)

service -> dbContext: Add(vantagem)
service -> dbContext: SaveChanges()

dbContext -> db: executarCadastroVantagem()
db --> dbContext: retornarDadosVantagem

dbContext --> service: retornarDadosVantagem

service --> Controlador: retornarDadosVantagem

Controlador -> User: exibirVantagemCriada
@enduml