@startuml
left to right direction

node "Navegador Web" as navegador

node "Servidor ASP.NET Core" as aspnet {
    
    node "Controllers" as controllers {
        [AlunoController]
        [ProfessorController]
        [EmpresaController]
        [VantagemController]
        [TransacaoController]
        [CodigoResgateController]
    }
    
    node "Services" as services {
        [AlunoService]
        [ProfessorService]
        [EmpresaService]
        [VantagemService]
        [TransacaoService]
        [CodigoResgateService]
    }
    
    node "Data Context" as context {
        [MeritSystemContext]
    }

    node "Entities" as entities {
        [Aluno]
        [Professor]
        [Empresa]
        [Vantagem]
        [Transacao]
        [CodigoResgate]
    }
}

database "Banco de Dados" as banco_dados

navegador --> controllers : HTTP/HTTPS
controllers --> services 
services --> context : DbSets (via MeritSystemContext)
context --> banco_dados : TCP/IP

@enduml
