// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoedaEstudantil.Data;

#nullable disable

namespace MoedaEstudantil.Migrations
{
    [DbContext(typeof(MeritSystemContext))]
    [Migration("20241125233822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MoedaEstudantil.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InstituicaoEnsino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("SaldoMoedas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e78518b6-27ec-46aa-b450-950beb7e0dcd"),
                            Curso = "Engenharia",
                            Documento = "12345678901",
                            Email = "joao.silva@example.com",
                            Endereco = "Rua das Flores, 123",
                            InstituicaoEnsino = "Universidade XYZ",
                            Nome = "João Silva",
                            SaldoMoedas = 100m,
                            Senha = "Senha123"
                        });
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("SaldoMoedas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d06df35d-f4f0-4d35-b517-8dff72774957"),
                            Documento = "33445566778",
                            Email = "contato@empresatech.com",
                            Nome = "Empresa Tech",
                            SaldoMoedas = 1000m,
                            Senha = "SenhaEmp123"
                        });
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("SaldoMoedas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("356763df-6948-4619-b6ed-66d457a2670a"),
                            Departamento = "Ciências Exatas",
                            Documento = "11223344556",
                            Email = "carlos.pereira@example.com",
                            Instituicao = "Universidade XYZ",
                            Nome = "Dr. Carlos Pereira",
                            SaldoMoedas = 500m,
                            Senha = "Senha789"
                        });
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("VantagemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("953d5a83-4d94-4ad2-888a-8c51b4a42057"),
                            AlunoId = new Guid("e78518b6-27ec-46aa-b450-950beb7e0dcd"),
                            Data = new DateTime(2024, 11, 25, 23, 38, 22, 144, DateTimeKind.Utc).AddTicks(5875),
                            Mensagem = "Participação em projeto de pesquisa",
                            ProfessorId = new Guid("356763df-6948-4619-b6ed-66d457a2670a"),
                            TipoTransacao = 0,
                            Valor = 100m
                        },
                        new
                        {
                            Id = new Guid("fc8cbcba-5f79-4760-9e78-b1188419a77d"),
                            AlunoId = new Guid("e78518b6-27ec-46aa-b450-950beb7e0dcd"),
                            Data = new DateTime(2024, 11, 25, 23, 38, 22, 144, DateTimeKind.Utc).AddTicks(5885),
                            Mensagem = "Para melhorar minhas habilidades",
                            TipoTransacao = 1,
                            Valor = 50m,
                            VantagemId = new Guid("ef800be2-26e2-4e2f-989d-d079ee5726b5")
                        });
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Vantagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Vantagens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef800be2-26e2-4e2f-989d-d079ee5726b5"),
                            Custo = 50m,
                            Descricao = "10% de desconto em qualquer curso online da Empresa Tech.",
                            EmpresaId = new Guid("d06df35d-f4f0-4d35-b517-8dff72774957"),
                            Nome = "Desconto em Curso Online"
                        });
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Transacao", b =>
                {
                    b.HasOne("MoedaEstudantil.Entities.Aluno", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoedaEstudantil.Entities.Professor", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Vantagem", b =>
                {
                    b.HasOne("MoedaEstudantil.Entities.Empresa", null)
                        .WithMany("VantagensOferecidas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Aluno", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Empresa", b =>
                {
                    b.Navigation("VantagensOferecidas");
                });

            modelBuilder.Entity("MoedaEstudantil.Entities.Professor", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
